name: Day 39 First CI

on:
  push:
    branches:
      - main

jobs:
  check-web-page:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v4

      - name: Check index.html
        run: |
          echo "Checking web page..."
          test -f index.html
          echo "index.html exists!"
      - name: Check SSH secret
        env:
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          test -n "$EC2_SSH_PRIVATE_KEY"
          echo "SSH secret is available!"
